- name: Install Apache and PHP for Ubuntu Servers
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install Apache and PHP for Rocky Linux Servers
  tags: apache,apache2,ubuntu
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "Rocky"

- name: Start httpd (Rocky)
  tags: apache,centos,httpd
  service: 
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Rocky"

- name: Change e-mail address for admin (Rocky)
  tags: apache,Rocky,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin martin.mato@ingrydacademy.com
  when: ansible_distribution == "Rocky"
  register: httpd

- name: Restart httpd (Rocky)
  tags: apache,rocky,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: Copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Install Unzip
  package:
    name: unzip

- name: Install OpenTofu
  unarchive:
    src: https://github.com/opentofu/opentofu/releases/download/v1.6.0-rc1/tofu_1.6.0-rc1_darwin_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

